"""Included new likes to the post model

Revision ID: d7f83cb21328
Revises: e3d2b535b7fe
Create Date: 2026-06-20 16:35:34.850094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7f83cb21328'
down_revision: Union[str, Sequence[str], None] = 'e3d2b535b7fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('new_likes', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'new_likes')
    # ### end Alembic commands ###
